<template>
  <div>
    *-has-text-left-mobile
*-has-text-left-touch
*-has-text-left-tablet-only
*-has-text-left-tablet
*-has-text-left-desktop-only
*-has-text-left-desktop
*-has-text-left-widescreen-only
*-has-text-left-widescreen
*-has-text-left-fullhd
  </div>
</template>
